### Python Numpy

In [5]:
import numpy as np

### Create an Array using list

In [47]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

### Create an Array using tuple

In [70]:
a = np.array((5, 1, 3, 2, 4))
a

array([5, 1, 3, 2, 4])

### Sorting Elements

In [69]:
a = [5, 4, 3, 2, 1]
np.sort(a)

array([1, 2, 3, 4, 5])

### Finding the Sum of the Elements of Array

In [61]:
a.sum()

85

### Finding the Standard Deviation of the Elements of Array

In [62]:
np.std(a)

2.3524350399711254

### Finding Mulidimensional Arrays

In [59]:
import numpy as np
a = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[2, 4, 2],[4, 6, 6],[8, 6, 2]]])
a.shape

(2, 3, 3)

In [60]:
a.ndim

3

### Accessing the Elements

In [65]:
a[1, 2, 0]

8

### Creating an Array of 5 Zeros

In [45]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

### Creating an Array of 5 Ones

In [44]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

### Creating an Array of 5 Fives

In [43]:
a = np.ones(5)*5
a

array([5., 5., 5., 5., 5.])

### Creating an Array of Integer Between 10 to 20

In [42]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Creating an Array of Even Integer Between 20 to 50

In [51]:
a = np.arange(20, 50, 2)
a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

### Creating Random Numbers

In [38]:
a = np.random.rand(5,3)  
a

array([[0.42760508, 0.90655127, 0.36122618],
       [0.50544683, 0.6419124 , 0.61175947],
       [0.49240414, 0.42997922, 0.89009599],
       [0.52302895, 0.10314719, 0.47099938],
       [0.76989925, 0.18645163, 0.96133879]])

### Generatingg Five Random Numbers

In [31]:
a = np.round(5*np.random.rand(5))
a

array([1., 3., 1., 1., 3.])

### Indexing and Selection

In [36]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Adding to the Elements of a Matrix

In [9]:
import numpy as np
A = np.round(10*np.random.rand(3, 3))
A

array([[4., 3., 9.],
       [6., 3., 9.],
       [7., 4., 5.]])

In [10]:
A+100

array([[104., 103., 109.],
       [106., 103., 109.],
       [107., 104., 105.]])

### Concatinating Horizontally

In [22]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
B = np.arange(1, 11).reshape(2, 5)
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
C = np.hstack((A, B))
C

array([[ 1,  2,  3,  1,  2,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8,  9, 10]])

### Concatinating Vertically

In [25]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
B = np.arange(1, 10).reshape(3, 3)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
C = np.vstack((A, B))
C

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Adding the Elements of Array

In [35]:
A = np.arange(1, 11)
%timeit np.sum(A)

5.29 µs ± 85.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
